import { Sora } from "next/font/google";
import "./globals.css";
import Nav from "./Component/Nav"

const sora = Sora({
  weight: ["300", "700"],
  variable: "--font-Sora",
  subsets: ["latin"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable}  antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
